version: 1
directus: 11.13.3
vendor: postgres
collections:
  - collection: web_pages
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: web_pages
      color: null
      display_template: '{{title}} ({{slug}})'
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: sort
      translations: null
      unarchive_value: draft
      versioning: false
    schema:
      name: web_pages
fields:
  - collection: web_pages
    field: id
    type: uuid
    meta:
      collection: web_pages
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: web_pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: status
    type: string
    meta:
      collection: web_pages
      conditions: null
      display: labels
      display_options:
        choices:
          - background: var(--theme--primary-background)
            color: var(--theme--primary)
            foreground: var(--theme--primary)
            text: $t:published
            value: published
          - background: var(--theme--background-normal)
            color: var(--theme--foreground)
            foreground: var(--theme--foreground)
            text: $t:draft
            value: draft
          - background: var(--theme--warning-background)
            color: var(--theme--warning)
            foreground: var(--theme--warning)
            text: $t:archived
            value: archived
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - color: var(--theme--primary)
            text: $t:published
            value: published
          - color: var(--theme--foreground)
            text: $t:draft
            value: draft
          - color: var(--theme--warning)
            text: $t:archived
            value: archived
      readonly: false
      required: false
      searchable: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: status
      table: web_pages
      data_type: character varying
      default_value: draft
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: sort
    type: integer
    meta:
      collection: web_pages
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: sort
      table: web_pages
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: user_created
    type: uuid
    meta:
      collection: web_pages
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      searchable: true
      sort: 8
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_created
      table: web_pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: web_pages
    field: date_created
    type: timestamp
    meta:
      collection: web_pages
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 9
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: web_pages
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: user_updated
    type: uuid
    meta:
      collection: web_pages
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      searchable: true
      sort: 10
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_updated
      table: web_pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: web_pages
    field: date_updated
    type: timestamp
    meta:
      collection: web_pages
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 11
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: web_pages
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: title
    type: string
    meta:
      collection: web_pages
      conditions: null
      display: raw
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options:
        placeholder: Page Title
        softLength: 128
        trim: true
      readonly: false
      required: true
      searchable: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: title
      table: web_pages
      data_type: character varying
      default_value: null
      max_length: 128
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: slug
    type: string
    meta:
      collection: web_pages
      conditions: null
      display: raw
      display_options: null
      field: slug
      group: null
      hidden: false
      interface: input
      note: null
      options:
        placeholder: Page Slug
        slug: true
        softLength: 128
        trim: true
      readonly: false
      required: true
      searchable: true
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: slug
      table: web_pages
      data_type: character varying
      default_value: null
      max_length: 128
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: web_pages
    field: parent_id
    type: uuid
    meta:
      collection: web_pages
      conditions: null
      display: null
      display_options: null
      field: parent_id
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
        enableLink: true
        template: '{{title}} ({{slug}})'
      readonly: false
      required: false
      searchable: true
      sort: 6
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: parent_id
      table: web_pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: web_pages
      foreign_key_column: id
  - collection: web_pages
    field: child_pages
    type: alias
    meta:
      collection: web_pages
      conditions: null
      display: null
      display_options: null
      field: child_pages
      group: null
      hidden: false
      interface: list-o2m
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 7
      special:
        - o2m
      translations: null
      validation: null
      validation_message: null
      width: full
systemFields:
  - collection: directus_activity
    field: timestamp
    schema:
      is_indexed: true
  - collection: directus_revisions
    field: parent
    schema:
      is_indexed: true
relations:
  - collection: web_pages
    field: user_updated
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: web_pages
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: web_pages
      column: user_updated
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: web_pages_user_updated_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: web_pages
    field: user_created
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: web_pages
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: web_pages
      column: user_created
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: web_pages_user_created_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: web_pages
    field: parent_id
    related_collection: web_pages
    meta:
      junction_field: null
      many_collection: web_pages
      many_field: parent_id
      one_allowed_collections: null
      one_collection: web_pages
      one_collection_field: null
      one_deselect_action: nullify
      one_field: child_pages
      sort_field: null
    schema:
      table: web_pages
      column: parent_id
      foreign_key_table: web_pages
      foreign_key_column: id
      constraint_name: web_pages_parent_id_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
